feat: use setting overrides for feature flags
forcedotcom/salesforcedx-vscode-experiments pull request #31
Opened 2024-08-15 19:44 UTC by jgellin-sf

### What does this PR do?

This PR introduces the `overrideSetting` field to the experiment definition API. This field is used to specify a VSCode config setting whose value overrides the random experiment value for non-expired experiments.

### What issues does this PR fix or reference?

@W-16328968@

2024-08-15 20:53 UTC, jgellin-sf commented on src/api.ts
> +  overrideSetting?: string;
yup

2024-08-15 20:55 UTC, gbockus-sf commented on src/internals/experimentState.ts
> +    if (experiments) {
How would this condition ever be false?

2024-08-15 20:56 UTC, jgellin-sf commented on src/internals/experimentState.ts
> +    if (experiments) {
if config changes before `assignExperiments`.

2024-08-15 22:02 UTC, gbockus-sf commented on src/internals/experimentState.ts
> +  private processOverrides(experiments: Experiment[]): void {
Should we make this just execute against the instance property?   I was debating discussion around editing parameter object again, but just having this method not take a parameter seems better.  We'd have to move the initial set on line 50 -> 46 to make this happen.

2024-08-16 16:54 UTC, gbockus-sf commented on src/internals/experimentState.ts
> +    if (experiments) {
experiments should just be an empty array then right?

2024-08-16 17:17 UTC, jgellin-sf commented on src/internals/experimentState.ts
> +  private processOverrides(experiments: Experiment[]): void {
Updated in https://github.com/forcedotcom/salesforcedx-vscode-experiments/pull/31/commits/0802e83b4306ad6e290ebb562c0a87bfa8a8357a

2024-08-16 21:10 UTC, jgellin-sf commented on src/internals/experimentState.ts
> +    if (experiments) {
Not if it's never been initialized. I went ahead and initialized it in the constructor and removed this check in https://github.com/forcedotcom/salesforcedx-vscode-experiments/pull/31/commits/c1e1ce6b28245d23e2863d5ba7f5e576f957357c

2024-08-19 16:30 UTC, gbockus-sf commented on src/internals/experimentState.ts
> +    if (experiments) {
Cool. Fine with it being initialized in the constructor.  I did think we defaulted it though with `private experiments: Experiment[] = [];` <insert how does any of this work gif ;) >

2024-08-19 16:39 UTC, gbockus-sf commented on src/internals/experimentState.ts
> +      this.processOverrides();
This is our only uncovered line in unit tests.  
![image](https://github.com/user-attachments/assets/1c08e52e-a5df-480a-9381-581d095d7af6)
I'll leave it to you if we're ok with that :)

2024-08-19 16:42 UTC, gbockus-sf commented on src/internals/experimentState.ts
> +    vscode.workspace.onDidChangeConfiguration(() => {
Sorry I missed this on the first pass. The disposable returned here by `onDidChangeColnfiguration` by this should be returned here and by the calling function to the consumer so that we can be cleaned up on extension exit.

2024-08-19 16:43 UTC, gbockus-sf requested changes
I missed the disposable on the first pass.  That one one test to consider and you're good to go.

2024-08-19 17:45 UTC, jgellin-sf commented on src/internals/experimentState.ts
> +      this.processOverrides();
Test coverage and listener disposal covered in https://github.com/forcedotcom/salesforcedx-vscode-experiments/pull/31/commits/36ece79443266d794db3288c723c1bbd50c8607c

2024-08-19 17:46 UTC, jgellin-sf commented on src/internals/experimentState.ts
> +    vscode.workspace.onDidChangeConfiguration(() => {
Test coverage and listener disposal covered in https://github.com/forcedotcom/salesforcedx-vscode-experiments/pull/31/commits/36ece79443266d794db3288c723c1bbd50c8607c

2024-08-19 20:50 UTC, gbockus-sf commented on src/internals/experimentState.ts
> +    this.disposables.push(vscode.workspace.onDidChangeConfiguration(this.handleConfigurationChange, this));
Sorry.  I was thinking we'd want the extension to deal with the disposable. It we want to keep it here why not `context.subscriptions.push(vscode.workspace.onDidChangeConfiguration(this.handleConfigurationChange, this));`

2024-08-19 21:39 UTC, jgellin-sf commented on src/internals/experimentState.ts
> +    this.disposables.push(vscode.workspace.onDidChangeConfiguration(this.handleConfigurationChange, this));
thanks for the tip. fixed in https://github.com/forcedotcom/salesforcedx-vscode-experiments/pull/31/commits/232b333438dc069ffd509079c1ef45b7e9d18c0a

2024-08-19 22:12 UTC, gbockus-sf approved these changes
Nice.  Looks good.  Will do deeper QE when we integrate with E4D

2024-08-19 22:23 UTC, merged